package preflop;

import rs.ac.uns.ftn.Player;
import rs.ac.uns.ftn.Logger;
import rs.ac.uns.ftn.handranking.Card;
import rs.ac.uns.ftn.GameState.ACTIONS_BEFORE_PLAYER;
import rs.ac.uns.ftn.GameState.PLAYER_POSITION;
import java.util.Arrays;

rule "Suited cards in sequence - All players fold - Early or Mid position"
    no-loop
	when
		Player((((holeCards.firstCard.rank >= Card.RANK_5 && holeCards.firstCard.rank <= Card.RANK_10 && holeCards.secondCard.rank == holeCards.firstCard.rank-1) ||
		         (holeCards.secondCard.rank >= Card.RANK_5 && holeCards.secondCard.rank <= Card.RANK_10 && holeCards.firstCard.rank == holeCards.secondCard.rank-1)) &&
		        holeCards.firstCard.suit == holeCards.secondCard.suit),
		        gameState.actionsBeforePlayer == ACTIONS_BEFORE_PLAYER.ALL_FOLD,
		        (gameState.playerPosition == PLAYER_POSITION.EARLY || gameState.playerPosition == PLAYER_POSITION.MID))
	    $l: Logger()
	then
		System.out.println("Suited cards in sequence - All players fold - Early or Mid position - Fold");
		modify($l){setText("Suited cards in sequence - All players fold - Early or Mid position - Fold")}
end

rule "Suited cards in sequence - All players fold - Late position"
    no-loop
	when
		Player((((holeCards.firstCard.rank >= Card.RANK_5 && holeCards.firstCard.rank <= Card.RANK_10 && holeCards.secondCard.rank == holeCards.firstCard.rank-1) ||
		         (holeCards.secondCard.rank >= Card.RANK_5 && holeCards.secondCard.rank <= Card.RANK_10 && holeCards.firstCard.rank == holeCards.secondCard.rank-1)) &&
		        holeCards.firstCard.suit == holeCards.secondCard.suit),
		        gameState.actionsBeforePlayer == ACTIONS_BEFORE_PLAYER.ALL_FOLD,
		        gameState.playerPosition == PLAYER_POSITION.LATE)
	    $l: Logger()
	then
		System.out.println("Suited cards in sequence - All players fold - Late position - Raise");
		modify($l){setText("Suited cards in sequence - All players fold - Late position - Raise")}
end

rule "Suited cards in sequence - All players fold - Blinds position"
    no-loop
	when
		Player((((holeCards.firstCard.rank >= Card.RANK_5 && holeCards.firstCard.rank <= Card.RANK_10 && holeCards.secondCard.rank == holeCards.firstCard.rank-1) ||
		         (holeCards.secondCard.rank >= Card.RANK_5 && holeCards.secondCard.rank <= Card.RANK_10 && holeCards.firstCard.rank == holeCards.secondCard.rank-1)) &&
		        holeCards.firstCard.suit == holeCards.secondCard.suit),
		        gameState.actionsBeforePlayer == ACTIONS_BEFORE_PLAYER.ALL_FOLD,
		        gameState.playerPosition == PLAYER_POSITION.BLINDS)
	    $l: Logger()
	then
		System.out.println("Suited cards in sequence - All players fold - Blinds position - Fold");
		modify($l){setText("Suited cards in sequence - All players fold - Blinds position - Fold")}
end

rule "Suited cards in sequence - One player called - Early position"
    no-loop
	when
		Player((((holeCards.firstCard.rank >= Card.RANK_5 && holeCards.firstCard.rank <= Card.RANK_10 && holeCards.secondCard.rank == holeCards.firstCard.rank-1) ||
		         (holeCards.secondCard.rank >= Card.RANK_5 && holeCards.secondCard.rank <= Card.RANK_10 && holeCards.firstCard.rank == holeCards.secondCard.rank-1)) &&
		        holeCards.firstCard.suit == holeCards.secondCard.suit),
		        gameState.actionsBeforePlayer == ACTIONS_BEFORE_PLAYER.ONE_CALL,
		        gameState.playerPosition == PLAYER_POSITION.EARLY)
	    $l: Logger()
	then
		System.out.println("Suited cards in sequence - One player called - Early position - Fold");
		modify($l){setText("Suited cards in sequence - One player called - Early position - Fold")}
end

rule "Suited cards in sequence - One player called - Not Early position"
    no-loop
	when
		Player((((holeCards.firstCard.rank >= Card.RANK_5 && holeCards.firstCard.rank <= Card.RANK_10 && holeCards.secondCard.rank == holeCards.firstCard.rank-1) ||
		         (holeCards.secondCard.rank >= Card.RANK_5 && holeCards.secondCard.rank <= Card.RANK_10 && holeCards.firstCard.rank == holeCards.secondCard.rank-1)) &&
		        holeCards.firstCard.suit == holeCards.secondCard.suit),
		        gameState.actionsBeforePlayer == ACTIONS_BEFORE_PLAYER.ONE_CALL,
		        gameState.playerPosition != PLAYER_POSITION.EARLY)
	    $l: Logger()
	then
		System.out.println("Suited cards in sequence - One player called - Not Early position - Call");
		modify($l){setText("Suited cards in sequence - One player called - Not Early position - Call")}
end

rule "Suited cards in sequence - One player raised or Reraised"
    no-loop
	when
		Player((((holeCards.firstCard.rank >= Card.RANK_5 && holeCards.firstCard.rank <= Card.RANK_10 && holeCards.secondCard.rank == holeCards.firstCard.rank-1) ||
		         (holeCards.secondCard.rank >= Card.RANK_5 && holeCards.secondCard.rank <= Card.RANK_10 && holeCards.firstCard.rank == holeCards.secondCard.rank-1)) &&
		        holeCards.firstCard.suit == holeCards.secondCard.suit),
		        (Arrays.asList(ACTIONS_BEFORE_PLAYER.ONE_RAISE, ACTIONS_BEFORE_PLAYER.RE_RAISE) contains gameState.actionsBeforePlayer))
	    $l: Logger()
	then
		System.out.println("Suited cards in sequence - One player raised or Reraised - Fold");
		modify($l){setText("Suited cards in sequence - One player raised or Reraised - Fold")}
end